- name: ServiceNow Create New Incident Demo
  hosts: localhost
  gather_facts: no
  collections:
    - servicenow.servicenow

  tasks:
    - name: Create new incident
      servicenow.itsm.incident:
        state: new
        short_description: Demo incident
        instance:
          host: "https://{{ SNOW_INSTANCE }}.service-now.com"
          username: "{{ SNOW_USERNAME }}"
          password: "{{ SNOW_PASSWORD }}"
      register: new_incident

    - name: Show new incident
      ansible.builtin.debug:
        var: new_incident
